/**
 * API documentation
 * To use this api you need an access token. To get the token, send a post request with your email address to api-users resource and one will be send to your. See below for information on how to use this api and if you have any questions you can contact us at helpdesk@laji.fi.  Place refer to [schema.laji.fi](http://schema.laji.fi/) for more information about the used vocabulary
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Collection {
    /**
     * More descriptive name for the collection
     */
    longName?: string;

    /**
     * Whether or not this collection has sub collections
     */
    hasChildren?: boolean;

    id: string;

    dateEdited?: Date;

    /**
     * en
     */
    dateCreated?: Date;

    /**
     * Team that owns the record and can edit it.
     */
    owner?: string;

    /**
     * Official abbreviation (or acronym) for this collection
     */
    abbreviation?: string;

    /**
     * Name of the collection in different languages. (Not name of collection database.) If lang parameter is 'multi' this will be a lang object instead of a string or an array of strings!
     */
    collectionName?: string;

    /**
     * Type of the collection.
     */
    collectionType?: string;

    /**
     *  If lang parameter is 'multi' this will be a lang object instead of a string or an array of strings!
     */
    description?: string;

    /**
     * Lowest common taxon (for example, scientific name of an order) If lang parameter is 'multi' this will be a lang object instead of a string or an array of strings!
     */
    taxonomicCoverage?: string;

    /**
     * Free-text notes
     */
    notes?: string;

    /**
     * Smallest common geographical area (for example, country or continent name) If lang parameter is 'multi' this will be a lang object instead of a string or an array of strings!
     */
    geographicCoverage?: string;

    /**
     * Concise definition of the coverage, if not clear from name or description. For example, 'Winter birds of Finland' If lang parameter is 'multi' this will be a lang object instead of a string or an array of strings!
     */
    coverageBasis?: string;

    /**
     * Methods used when creating this collection, if they are standardized. Includes information on items such as census methods, tools, instrument calibration and software. If lang parameter is 'multi' this will be a lang object instead of a string or an array of strings!
     */
    methods?: string;

    /**
     * When were the specimens/data collected? If lang parameter is 'multi' this will be a lang object instead of a string or an array of strings!
     */
    temporalCoverage?: string;

    /**
     * License which is used when publishing data that belongs to this collection.
     */
    intellectualRights?: string;

    /**
     * How can Luomus publish the data, if it is owned by third party?
     */
    publicationTerms?: string;

    /**
     * Description of possible restrictions on publication of the data (for example, is there data about endangered species which should be concealed?) If lang parameter is 'multi' this will be a lang object instead of a string or an array of strings!
     */
    publicationDescription?: string;

    /**
     * Quarantine period in years after which data is opened
     */
    dataQuarantinePeriod?: number;

    /**
     * Legal basis for concealment or quarantine If lang parameter is 'multi' this will be a lang object instead of a string or an array of strings!
     */
    concealmentBasis?: string;

    /**
     * How many specimens, records or such does the collection contain? Fill in approximate number, describe more in notes if necessary.
     */
    collectionSize?: string;

    /**
     * PUBLIC: all data can be published; PROTECTED: exact locality is hidden; PRIVATE: most of the data is hidden. If blank means same as public
     */
    publicityRestrictions?: string;

    /**
     * How many percent of the collection is in digital form, e.g. in a database or Excel file? Fill in approximate number, describe more in notes if necessary.
     */
    digitizedSize?: string;

    /**
     * Which parent or larger dataset this is part of.
     */
    isPartOf?: string;

    /**
     * Person(s) responsible for the collection (Lastname, Firstname; Lastname, Firstname).
     */
    personResponsible?: string;

    /**
     * Personal or general (e.g. group of people in the organisation) email address to reach the person(s) responsible.
     */
    contactEmail?: string;

    /**
     * Example how to cite this collection in a scientific article, if using organization, name and abbreviation is not enough.
     */
    citation?: string;

    /**
     * Web address (URL) with more info about the collection If lang parameter is 'multi' this will be a lang object instead of a string or an array of strings!
     */
    onlineUrl?: string;

    /**
     * Quality estimation for the data in this collection
     */
    dataQuality?: string;

    metadataCreator?: string;

    /**
     * Indication of how comprehensive the information on this form is
     */
    metadataStatus?: string;

    /**
     * How many TYPE specimens does the collection contain?  Fill in approximate number, describe more in notes if necessary.
     */
    typesSize?: string;

    /**
     * Name of the data owner; ONLY fill this if the owner is not clear from the parent collection name(s). E.g. \"University of Oulu\" or \"Luomus\"
     */
    intellectualOwner?: string;

    /**
     * Description of the rights governing the data (for example, what contracts have been made about this). If left blank, Luomus data policy is followed. If lang parameter is 'multi' this will be a lang object instead of a string or an array of strings!
     */
    intellectualDescription?: string;

    /**
     * Language the specimen data is (mainly) written in, if applicable.
     */
    language?: string;

    /**
     * Reason for this edit or notes about it.
     */
    editNotes?: string;

    downloadRequestHandler?: Array<string>;

    secureLevel?: string;

}
