/**
 * API documentation
 * To use this api you need an access token. To get the token, send a post request with your email address to api-users resource and one will be send to your. See below for information on how to use this api and if you have any questions you can contact us at helpdesk@laji.fi.  Place refer to [schema.laji.fi](http://schema.laji.fi/) for more information about the used vocabulary
 *
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Gatherings {
    /**
     * Unique ID for the object. This will be automatically generated.
     */
    id?: string;

    /**
     * AFE grid name
     */
    aFEQuadrat?: string;

    /**
     * UTM grid name
     */
    uTMQuadrat?: string;

    /**
     * Separate multiple names with commas, from generic to specific. (E.g. Etelä-Suomen lääni, Uusimaa)
     */
    administrativeProvince?: string;

    /**
     * Altitude form sea level in meters, or range (E.g. 90, or 80-100). No GPS altitude here.
     */
    alt?: string;

    areaDetail?: string;

    /**
     * Write associated taxa names here, separated by a semicolon (;). E.g.: \\\"Betula pendula; Betula pubescens; Poaceae\\\".
     */
    associatedObservationTaxa?: string;

    associatedSpecimenTaxa?: string;

    /**
     * Formal abbreviation. For Finnish eliömaakunnat, use Finnish abbreviation.
     */
    biologicalProvince?: string;

    /**
     * Name of an expedition or such
     */
    collectingEventName?: string;

    /**
     * Informal notes about the coordinates
     */
    coordinateNotes?: string;

    /**
     * Maximum error of coordinates in meters
     */
    coordinateRadius?: string;

    /**
     * Use for NEW SPECIMENS: Where the coordinates have been acquired
     */
    coordinateSource?: Gatherings.CoordinateSourceEnum;

    /**
     * Examples of different coordinate styles are at https://wiki.helsinki.fi/display/digit/Entering+specimen+data
     */
    coordinateSystem?: Gatherings.CoordinateSystemEnum;

    coordinatesGridYKJ?: string;

    coordinatesVerbatim?: string;

    /**
     * Country name in English, or 2-letter country code, or name from label
     */
    country?: string;

    dateBegin?: string;

    dateEnd?: string;

    /**
     * Date just as it appears on the label or other original source, no interpretation, errors and all
     */
    dateVerbatim?: string;

    /**
     * Depth in meters, or range (E.g. 0.9, or 0.8-1.0)
     */
    depth?: string;

    eventDate?: string;

    forestVegetationZone?: Gatherings.ForestVegetationZoneEnum;

    /**
     * Geological information about gathering
     */
    geometry?: models.Geometry;

    /**
     * Use for OLD SPECIMENS: What source was used to get coordinates from locality name
     */
    georeferenceSource?: Gatherings.GeoreferenceSourceEnum;

    /**
     * Formal habitat name or abbreviation. If several, separate with semicolons (E.g. 'OMT; OMaT')
     */
    habitatClassification?: string;

    /**
     * Informal description of the habitat
     */
    habitatDescription?: string;

    /**
     * If country is not known or not applicable, for example continent, ocean or large island
     */
    higherGeography?: string;

    /**
     * Latitude. For southern latitudes, use negative value.
     */
    latitude?: string;

    leg?: Array<string>;

    /**
     * Leg just as it appears in the label or other original source, no interpretation, errors and all
     */
    legVerbatim?: string;

    /**
     * Official name of the locality. Separate multiple names with commas, from generic to specific. No informal description here!
     */
    locality?: string;

    /**
     * Informal description of the exact locality, e.g. '5 km NE of city X, under stone bridge'
     */
    localityDescription?: string;

    /**
     * An unique identifier or code for the locality, if the locality has one (e.g. from SAPO-ontology)
     */
    localityID?: string;

    /**
     * Locality word-to-word as it appears on the label or other original source, errors and all
     */
    localityVerbatim?: string;

    /**
     * Longitude. For western longitudes, use negative value.
     */
    longitude?: string;

    /**
     * Municipality, commune or county
     */
    municipality?: string;

    /**
     * Free-text notes
     */
    notes?: string;

    projectTitle?: string;

    province?: string;

    /**
     * PUBLIC: all data can be published; PROTECTED: exact locality is hidden; PRIVATE: most of the data is hidden. If blank means same as public
     */
    publicityRestrictions?: Gatherings.PublicityRestrictionsEnum;

    samplingMethod?: Gatherings.SamplingMethodEnum;

    substrate?: string;

    temperature?: number;

    /**
     * Array of units
     */
    units?: Array<models.Units>;

    /**
     * Geological information about gathering in wgs84 format
     */
    wgs84Geometry?: models.Geometry;

    wgs84Latitude?: string;

    wgs84Longitude?: string;

    controlActivitiesNotes?: string;

    habitat?: Gatherings.HabitatEnum;

    /**
     * QName for MY.unit
     */
    hasUnit?: string;

    /**
     * QName for MM.image
     */
    images?: string;

    /**
     * Alkuperäislähteen käyttäjätunnus
     */
    legUserID?: Array<string>;

    predominantTree?: Gatherings.PredominantTreeEnum;

    /**
     * QName for MY.unit
     */
    unit?: string;

}
export namespace Gatherings {
    export enum CoordinateSourceEnum {
        CoordinateSourceGps = <any> 'MY.coordinateSourceGps',
        CoordinateSourcePeruskartta = <any> 'MY.coordinateSourcePeruskartta',
        CoordinateSourcePapermap = <any> 'MY.coordinateSourcePapermap',
        CoordinateSourceKotkamap = <any> 'MY.coordinateSourceKotkamap',
        CoordinateSourceKarttapaikka = <any> 'MY.coordinateSourceKarttapaikka',
        CoordinateSourceRetkikartta = <any> 'MY.coordinateSourceRetkikartta',
        CoordinateSourceOther = <any> 'MY.coordinateSourceOther',
        CoordinateSourceUnknown = <any> 'MY.coordinateSourceUnknown'
    }
    export enum CoordinateSystemEnum {
        CoordinateSystemYkj = <any> 'MY.coordinateSystemYkj',
        CoordinateSystemWgs84 = <any> 'MY.coordinateSystemWgs84',
        CoordinateSystemWgs84dms = <any> 'MY.coordinateSystemWgs84dms',
        CoordinateSystemKkj = <any> 'MY.coordinateSystemKkj',
        CoordinateSystemEtrsTm35fin = <any> 'MY.coordinateSystemEtrs-tm35fin',
        CoordinateSystemDd = <any> 'MY.coordinateSystemDd',
        CoordinateSystemDms = <any> 'MY.coordinateSystemDms'
    }
    export enum ForestVegetationZoneEnum {
        ForestVegetationZone1a = <any> 'MY.forestVegetationZone1a',
        ForestVegetationZone1b = <any> 'MY.forestVegetationZone1b',
        ForestVegetationZone2a = <any> 'MY.forestVegetationZone2a',
        ForestVegetationZone2b = <any> 'MY.forestVegetationZone2b',
        ForestVegetationZone3a = <any> 'MY.forestVegetationZone3a',
        ForestVegetationZone3b = <any> 'MY.forestVegetationZone3b',
        ForestVegetationZone3c = <any> 'MY.forestVegetationZone3c',
        ForestVegetationZone4a = <any> 'MY.forestVegetationZone4a',
        ForestVegetationZone4b = <any> 'MY.forestVegetationZone4b',
        ForestVegetationZone4c = <any> 'MY.forestVegetationZone4c',
        ForestVegetationZone4d = <any> 'MY.forestVegetationZone4d'
    }
    export enum GeoreferenceSourceEnum {
        GeoreferenceSourceKotka = <any> 'MY.georeferenceSourceKotka',
        GeoreferenceSourceKarttapaikka = <any> 'MY.georeferenceSourceKarttapaikka',
        GeoreferenceSourcePaikkatietoikkuna = <any> 'MY.georeferenceSourcePaikkatietoikkuna',
        GeoreferenceSourceKarjalankartat = <any> 'MY.georeferenceSourceKarjalankartat',
        GeoreferenceSourceRetkikartta = <any> 'MY.georeferenceSourceRetkikartta',
        GeoreferenceSourceGoogle = <any> 'MY.georeferenceSourceGoogle',
        GeoreferenceSourcePeruskartta = <any> 'MY.georeferenceSourcePeruskartta',
        GeoreferenceSourcePapermap = <any> 'MY.georeferenceSourcePapermap',
        GeoreferenceSourceOtherpaper = <any> 'MY.georeferenceSourceOtherpaper',
        GeoreferenceSourceOtherweb = <any> 'MY.georeferenceSourceOtherweb',
        GeoreferenceSourceCatalogue = <any> 'MY.georeferenceSourceCatalogue',
        GeoreferenceSourceBiogeomancer = <any> 'MY.georeferenceSourceBiogeomancer',
        GeoreferenceSourceGeolocate = <any> 'MY.georeferenceSourceGeolocate',
        GeoreferenceSourceOther = <any> 'MY.georeferenceSourceOther',
        GeoreferenceSourceUnknown = <any> 'MY.georeferenceSourceUnknown'
    }
    export enum PublicityRestrictionsEnum {
        PublicityRestrictionsPublic = <any> 'MZ.publicityRestrictionsPublic',
        PublicityRestrictionsProtected = <any> 'MZ.publicityRestrictionsProtected',
        PublicityRestrictionsPrivate = <any> 'MZ.publicityRestrictionsPrivate'
    }
    export enum SamplingMethodEnum {
        SamplingMethodLight = <any> 'MY.samplingMethodLight',
        SamplingMethodPitfall = <any> 'MY.samplingMethodPitfall',
        SamplingMethodNet = <any> 'MY.samplingMethodNet',
        SamplingMethodMalaise = <any> 'MY.samplingMethodMalaise',
        SamplingMethodSoilsample = <any> 'MY.samplingMethodSoilsample',
        SamplingMethodSweeping = <any> 'MY.samplingMethodSweeping',
        SamplingMethodBait = <any> 'MY.samplingMethodBait',
        SamplingMethodBaittrap = <any> 'MY.samplingMethodBaittrap',
        SamplingMethodFeromonetrap = <any> 'MY.samplingMethodFeromonetrap',
        SamplingMethodWindowtrap = <any> 'MY.samplingMethodWindowtrap',
        SamplingMethodPantrap = <any> 'MY.samplingMethodPantrap',
        SamplingMethodYellowpan = <any> 'MY.samplingMethodYellowpan',
        SamplingMethodYellowWindowTrap = <any> 'MY.samplingMethodYellowWindowTrap',
        SamplingMethodYellowtrap = <any> 'MY.samplingMethodYellowtrap',
        SamplingMethodTrap = <any> 'MY.samplingMethodTrap',
        SamplingMethodLightTrap = <any> 'MY.samplingMethodLightTrap',
        SamplingMethodSieve = <any> 'MY.samplingMethodSieve',
        SamplingMethodMistnet = <any> 'MY.samplingMethodMistnet',
        SamplingMethodHand = <any> 'MY.samplingMethodHand',
        SamplingMethodCarnet = <any> 'MY.samplingMethodCarnet',
        SamplingMethodDropping = <any> 'MY.samplingMethodDropping',
        SamplingMethodExovo = <any> 'MY.samplingMethodExovo',
        SamplingMethodElarva = <any> 'MY.samplingMethodElarva',
        SamplingMethodEpupa = <any> 'MY.samplingMethodEpupa',
        SamplingMethodReared = <any> 'MY.samplingMethodReared',
        SamplingMethodEclectortrap = <any> 'MY.samplingMethodEclectortrap',
        SamplingMethodSifting = <any> 'MY.samplingMethodSifting',
        SamplingMethodBoard = <any> 'MY.samplingMethodBoard',
        SamplingMethodDrag = <any> 'MY.samplingMethodDrag',
        SamplingMethodTriangleDrag = <any> 'MY.samplingMethodTriangleDrag',
        SamplingMethodFishNet = <any> 'MY.samplingMethodFishNet',
        SamplingMethodElectrofishing = <any> 'MY.samplingMethodElectrofishing',
        SamplingMethodAngleFishing = <any> 'MY.samplingMethodAngleFishing',
        SamplingMethodFishTrap = <any> 'MY.samplingMethodFishTrap',
        SamplingMethodSeine = <any> 'MY.samplingMethodSeine',
        SamplingMethodTrawling = <any> 'MY.samplingMethodTrawling',
        SamplingMethodOther = <any> 'MY.samplingMethodOther',
        SamplingMethodDiving = <any> 'MY.samplingMethodDiving',
        SamplingMethodBeamTrawl = <any> 'MY.samplingMethodBeamTrawl',
        SamplingMethodDigging = <any> 'MY.samplingMethodDigging'
    }
    export enum HabitatEnum {
        HabitatEnumValue1 = <any> 'MY.habitatEnumValue1',
        HabitatEnumValue2 = <any> 'MY.habitatEnumValue2',
        HabitatEnumValue3 = <any> 'MY.habitatEnumValue3',
        HabitatEnumValue4 = <any> 'MY.habitatEnumValue4',
        HabitatEnumValue5 = <any> 'MY.habitatEnumValue5',
        HabitatEnumValue6 = <any> 'MY.habitatEnumValue6',
        HabitatEnumValue7 = <any> 'MY.habitatEnumValue7',
        HabitatEnumValue13 = <any> 'MY.habitatEnumValue13',
        HabitatEnumValue14 = <any> 'MY.habitatEnumValue14',
        HabitatEnumValue15 = <any> 'MY.habitatEnumValue15',
        HabitatEnumValue21 = <any> 'MY.habitatEnumValue21',
        HabitatEnumValue32 = <any> 'MY.habitatEnumValue32',
        HabitatEnumValue33 = <any> 'MY.habitatEnumValue33',
        HabitatEnumValue34 = <any> 'MY.habitatEnumValue34',
        HabitatEnumValue35 = <any> 'MY.habitatEnumValue35',
        HabitatEnumValue36 = <any> 'MY.habitatEnumValue36',
        HabitatEnumValue39 = <any> 'MY.habitatEnumValue39',
        HabitatEnumValue37 = <any> 'MY.habitatEnumValue37',
        HabitatEnumValue38 = <any> 'MY.habitatEnumValue38',
        HabitatEnumValue40 = <any> 'MY.habitatEnumValue40',
        HabitatEnumValue41 = <any> 'MY.habitatEnumValue41',
        HabitatEnumValue42 = <any> 'MY.habitatEnumValue42',
        HabitatEnumValue43 = <any> 'MY.habitatEnumValue43',
        HabitatEnumValue44 = <any> 'MY.habitatEnumValue44',
        HabitatEnumValue45 = <any> 'MY.habitatEnumValue45',
        HabitatEnumValue46 = <any> 'MY.habitatEnumValue46',
        HabitatEnumValue47 = <any> 'MY.habitatEnumValue47',
        HabitatEnumValue48 = <any> 'MY.habitatEnumValue48',
        HabitatEnumValue49 = <any> 'MY.habitatEnumValue49',
        HabitatEnumValue50 = <any> 'MY.habitatEnumValue50',
        HabitatEnumValue51 = <any> 'MY.habitatEnumValue51',
        HabitatEnumValue52 = <any> 'MY.habitatEnumValue52',
        HabitatEnumValue53 = <any> 'MY.habitatEnumValue53',
        HabitatEnumValue54 = <any> 'MY.habitatEnumValue54',
        HabitatEnumValue55 = <any> 'MY.habitatEnumValue55',
        HabitatEnumValue56 = <any> 'MY.habitatEnumValue56',
        HabitatEnumValue57 = <any> 'MY.habitatEnumValue57',
        HabitatEnumValue58 = <any> 'MY.habitatEnumValue58',
        HabitatEnumValue59 = <any> 'MY.habitatEnumValue59',
        HabitatEnumValue60 = <any> 'MY.habitatEnumValue60',
        HabitatEnumValue61 = <any> 'MY.habitatEnumValue61',
        HabitatEnumValue62 = <any> 'MY.habitatEnumValue62',
        HabitatEnumValue63 = <any> 'MY.habitatEnumValue63',
        HabitatEnumValue64 = <any> 'MY.habitatEnumValue64',
        HabitatEnumValue65 = <any> 'MY.habitatEnumValue65',
        HabitatEnumValue66 = <any> 'MY.habitatEnumValue66',
        HabitatEnumValue67 = <any> 'MY.habitatEnumValue67',
        HabitatEnumValue68 = <any> 'MY.habitatEnumValue68',
        HabitatEnumValue69 = <any> 'MY.habitatEnumValue69',
        HabitatEnumValue70 = <any> 'MY.habitatEnumValue70',
        HabitatEnumValue71 = <any> 'MY.habitatEnumValue71',
        HabitatEnumValue72 = <any> 'MY.habitatEnumValue72',
        HabitatEnumValue73 = <any> 'MY.habitatEnumValue73',
        HabitatEnumValue74 = <any> 'MY.habitatEnumValue74',
        HabitatEnumValue75 = <any> 'MY.habitatEnumValue75',
        HabitatEnumValue76 = <any> 'MY.habitatEnumValue76',
        HabitatEnumValue77 = <any> 'MY.habitatEnumValue77',
        HabitatEnumValue78 = <any> 'MY.habitatEnumValue78',
        HabitatEnumValue79 = <any> 'MY.habitatEnumValue79',
        HabitatEnumValue80 = <any> 'MY.habitatEnumValue80',
        HabitatEnumValue81 = <any> 'MY.habitatEnumValue81',
        HabitatEnumValue82 = <any> 'MY.habitatEnumValue82',
        HabitatEnumValue83 = <any> 'MY.habitatEnumValue83',
        HabitatEnumValue84 = <any> 'MY.habitatEnumValue84',
        HabitatEnumValue85 = <any> 'MY.habitatEnumValue85',
        HabitatEnumValue86 = <any> 'MY.habitatEnumValue86',
        HabitatEnumValue87 = <any> 'MY.habitatEnumValue87',
        HabitatEnumValue88 = <any> 'MY.habitatEnumValue88',
        HabitatEnumValue89 = <any> 'MY.habitatEnumValue89',
        HabitatEnumValue90 = <any> 'MY.habitatEnumValue90',
        HabitatEnumValue91 = <any> 'MY.habitatEnumValue91',
        HabitatEnumValue92 = <any> 'MY.habitatEnumValue92',
        HabitatEnumValue93 = <any> 'MY.habitatEnumValue93',
        HabitatEnumValue94 = <any> 'MY.habitatEnumValue94',
        HabitatEnumValue95 = <any> 'MY.habitatEnumValue95',
        HabitatEnumValue96 = <any> 'MY.habitatEnumValue96',
        HabitatEnumValue97 = <any> 'MY.habitatEnumValue97',
        HabitatEnumValue98 = <any> 'MY.habitatEnumValue98',
        HabitatEnumValue99 = <any> 'MY.habitatEnumValue99',
        HabitatEnumValue100 = <any> 'MY.habitatEnumValue100',
        HabitatEnumValue101 = <any> 'MY.habitatEnumValue101',
        HabitatEnumValue102 = <any> 'MY.habitatEnumValue102',
        HabitatEnumValue103 = <any> 'MY.habitatEnumValue103',
        HabitatEnumValue104 = <any> 'MY.habitatEnumValue104',
        HabitatEnumValue105 = <any> 'MY.habitatEnumValue105',
        HabitatEnumValue106 = <any> 'MY.habitatEnumValue106',
        HabitatEnumValue107 = <any> 'MY.habitatEnumValue107',
        HabitatEnumValue108 = <any> 'MY.habitatEnumValue108'
    }
    export enum PredominantTreeEnum {
        PredominantTreeSpruce = <any> 'MY.predominantTreeSpruce',
        PredominantTreePine = <any> 'MY.predominantTreePine',
        PredominantTreeBirch = <any> 'MY.predominantTreeBirch',
        PredominantTreeAlder = <any> 'MY.predominantTreeAlder',
        PredominantTreeAspen = <any> 'MY.predominantTreeAspen',
        PredominantTreeOak = <any> 'MY.predominantTreeOak'
    }
}
