/**
 * API documentation
 * To use this api you need an access token. To get the token, send a post request with your email address to api-users resource and one
 * will be send to your. See below for information on how to use this api and if you have any questions you can contact us at
 * helpdesk@laji.fi.  Place refer to [schema.laji.fi](http://schema.laji.fi/) for more information about the used vocabulary
 *
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Units {
    /**
     * Unique ID for the object. This will be automatically generated.
     */
    id?: string;

    /**
     * Diameter at breast height, in centimeters
     */
    dBH?: string;

    /**
     * Leave empty if no sample taken, or if the sample was recorded separately
     */
    dNASampleLocation?: string;

    abundanceString?: string;

    age?: string;

    ageNotes?: string;

    ankleInMillimeters?: Array<string>;

    beakInMillimeters?: Array<string>;

    causeOfDeath?: string;

    chemistry?: string;

    /**
     * Numeric or other description on the amount of individuals (or sprouts, fruiting bodies or such) in the specimen.
     * Sexes and juveniles can be specified like so: 1m2f3j (=1 male, 2 females, 3 juveniles)
     */
    count?: string;

    decayStage?: string;

    genotype?: string;

    gonadInMillimeters?: Array<string>;

    growthMediumName?: string;

    growthOtherConditions?: string;

    growthTemperature?: string;

    /**
     * Array of identifications
     */
    identifications?: Array<models.Identifications>;

    /**
     * Non-negative integer
     */
    individualCount?: number;

    informalNameString?: string;

    infrasubspecificSubdivision?: string;

    lengthInMillimeters?: Array<string>;

    lifeStage?: Units.LifeStageEnum;

    lifeStageDescription?: string;

    macroscopy?: string;

    measurement?: Array<string>;

    microscopy?: string;

    mutant?: string;

    /**
     * Free-text notes
     */
    notes?: string;

    /**
     * Abundance of the taxon in the field
     */
    populationAbundance?: string;

    preparations?: string;

    /**
     * PUBLIC: all data can be published; PROTECTED: exact locality is hidden; PRIVATE: most of the data is hidden.
     * If blank means same as public
     */
    publicityRestrictions?: Units.PublicityRestrictionsEnum;

    recordBasis?: Units.RecordBasisEnum;

    recordParts?: Units.RecordPartsEnum;

    ring?: string;

    sex?: Units.SexEnum;

    sexNotes?: string;

    tasteNotes?: string;

    tailInMillimeters?: Array<string>;

    /**
     * QName for MY.typeSpecimen
     */
    typeSpecimen?: string;

    /**
     * Array of typeSpecimens
     */
    typeSpecimens?: Array<models.TypeSpecimens>;

    weightInGrams?: Array<string>;

    wingInMillimeters?: Array<string>;

    alive?: boolean;

    atlasCode?: Units.AtlasCodeEnum;

    breeding?: boolean;

    /**
     * Määrä
     */
    countOfOccurrences?: number;

    /**
     * QName for MY.identification
     */
    hasIdentification?: string;

    /**
     * QName for MY.subUnit
     */
    hasSubUnit?: string;

    /**
     * QName for MX.taxon
     */
    hostID?: string;

    /**
     * QName for MY.identification
     */
    identification?: string;

    /**
     * QName for MM.image
     */
    images?: string;

    movingStatus?: string;

    nativeStatus?: Units.NativeStatusEnum;

    plantLifeStage?: Units.PlantLifeStageEnum;

    plantStatusCode?: Units.PlantStatusCodeEnum;

    /**
     * Main method of preservation
     */
    preservation?: Units.PreservationEnum;

    smell?: Units.SmellEnum;

    smellNotes?: string;

    substrateClassification?: Units.SubstrateClassificationEnum;

    substrateNotes?: string;

    substrateSpecies?: string;

    taste?: Units.TasteEnum;

    taxonConfidence?: Units.TaxonConfidenceEnum;

    twitched?: string;

    /**
     * instance of unitGathering
     */
    unitGathering?: models.UnitGathering;

    unitType?: Array<string>;

    /**
     * Decimal number
     */
    wingLengthAccuracy?: number;

    /**
     * Decimal number
     */
    wingLengthMax?: number;

    /**
     * Decimal number
     */
    wingLengthMin?: number;

}
export namespace Units {
    export enum LifeStageEnum {
        LifeStageEgg = <any> 'MY.lifeStageEgg',
        LifeStageLarva = <any> 'MY.lifeStageLarva',
        LifeStagePupa = <any> 'MY.lifeStagePupa',
        LifeStageJuvenile = <any> 'MY.lifeStageJuvenile',
        LifeStageNymph = <any> 'MY.lifeStageNymph',
        LifeStageSubimago = <any> 'MY.lifeStageSubimago',
        LifeStageImmature = <any> 'MY.lifeStageImmature',
        LifeStageAdult = <any> 'MY.lifeStageAdult',
        LifeStageFertile = <any> 'MY.lifeStageFertile',
        LifeStageSterile = <any> 'MY.lifeStageSterile',
        LifeStageTadpole = <any> 'MY.lifeStageTadpole',
        LifeStageDead = <any> 'MY.lifeStageDead',
        LifeStageAlive = <any> 'MY.lifeStageAlive'
    }
    export enum PublicityRestrictionsEnum {
        PublicityRestrictionsPublic = <any> 'MZ.publicityRestrictionsPublic',
        PublicityRestrictionsProtected = <any> 'MZ.publicityRestrictionsProtected',
        PublicityRestrictionsPrivate = <any> 'MZ.publicityRestrictionsPrivate'
    }
    export enum RecordBasisEnum {
        RecordBasisPreservedSpecimen = <any> 'MY.recordBasisPreservedSpecimen',
        RecordBasisFossilSpecimen = <any> 'MY.recordBasisFossilSpecimen',
        RecordBasisSubfossilSpecimen = <any> 'MY.recordBasisSubfossilSpecimen',
        RecordBasisHumanObservation = <any> 'MY.recordBasisHumanObservation',
        RecordBasisMachineObservation = <any> 'MY.recordBasisMachineObservation',
        RecordBasisLivingSpecimen = <any> 'MY.recordBasisLivingSpecimen',
        RecordBasisMicrobialSpecimen = <any> 'MY.recordBasisMicrobialSpecimen',
        RecordBasisHumanObservationSeen = <any> 'MY.recordBasisHumanObservationSeen',
        RecordBasisHumanObservationHeard = <any> 'MY.recordBasisHumanObservationHeard',
        RecordBasisHumanObservationPhoto = <any> 'MY.recordBasisHumanObservationPhoto',
        RecordBasisHumanObservationIndirect = <any> 'MY.recordBasisHumanObservationIndirect',
        RecordBasisHumanObservationHandled = <any> 'MY.recordBasisHumanObservationHandled',
        RecordBasisHumanObservationVideo = <any> 'MY.recordBasisHumanObservationVideo',
        RecordBasisHumanObservationAudio = <any> 'MY.recordBasisHumanObservationAudio',
        RecordBasisMachineObservationVideo = <any> 'MY.recordBasisMachineObservationVideo',
        RecordBasisMachineObservationAudio = <any> 'MY.recordBasisMachineObservationAudio',
        RecordBasisMachineObservationGeologger = <any> 'MY.recordBasisMachineObservationGeologger',
        RecordBasisMachineObservationSatelliteTransmitter = <any> 'MY.recordBasisMachineObservationSatelliteTransmitter',
        RecordBasisLiterature = <any> 'MY.recordBasisLiterature'
    }
    export enum RecordPartsEnum {
        RecordPartsBones = <any> 'MY.recordPartsBones',
        RecordPartsAntler = <any> 'MY.recordPartsAntler',
        RecordPartsHead = <any> 'MY.recordPartsHead',
        RecordPartsSkull = <any> 'MY.recordPartsSkull',
        RecordPartsSkin = <any> 'MY.recordPartsSkin',
        RecordPartsWing = <any> 'MY.recordPartsWing',
        RecordPartsTail = <any> 'MY.recordPartsTail',
        RecordPartsTissue = <any> 'MY.recordPartsTissue',
        RecordPartsFeather = <any> 'MY.recordPartsFeather',
        RecordPartsEgg = <any> 'MY.recordPartsEgg',
        RecordPartsIntestine = <any> 'MY.recordPartsIntestine',
        RecordPartsGonad = <any> 'MY.recordPartsGonad',
        RecordPartsSeed = <any> 'MY.recordPartsSeed',
        RecordPartsNest = <any> 'MY.recordPartsNest',
        RecordPartsFaeces = <any> 'MY.recordPartsFaeces',
        RecordPartsFeedingMarks = <any> 'MY.recordPartsFeedingMarks',
        RecordPartsTracks = <any> 'MY.recordPartsTracks',
        RecordPartsScale = <any> 'MY.recordPartsScale',
        RecordPartsFin = <any> 'MY.recordPartsFin',
        RecordPartsFull = <any> 'MY.recordPartsFull',
        RecordPartsPart = <any> 'MY.recordPartsPart',
        RecordPartsActiveCulture = <any> 'MY.recordPartsActiveCulture',
        RecordPartsCutting = <any> 'MY.recordPartsCutting',
        RecordPartsVegetativePart = <any> 'MY.recordPartsVegetativePart',
        RecordPartsFreezeDried = <any> 'MY.recordPartsFreezeDried',
        RecordPartsDryIce = <any> 'MY.recordPartsDryIce',
        RecordPartsDNA = <any> 'MY.recordPartsDNA'
    }
    export enum SexEnum {
        SexM = <any> 'MY.sexM',
        SexF = <any> 'MY.sexF',
        SexW = <any> 'MY.sexW',
        SexU = <any> 'MY.sexU',
        SexN = <any> 'MY.sexN',
        SexX = <any> 'MY.sexX',
        SexE = <any> 'MY.sexE',
        SexC = <any> 'MY.sexC'
    }
    export enum AtlasCodeEnum {
        AtlasCodeEnum1 = <any> 'MY.atlasCodeEnum1',
        AtlasCodeEnum2 = <any> 'MY.atlasCodeEnum2',
        AtlasCodeEnum3 = <any> 'MY.atlasCodeEnum3',
        AtlasCodeEnum4 = <any> 'MY.atlasCodeEnum4',
        AtlasCodeEnum5 = <any> 'MY.atlasCodeEnum5',
        AtlasCodeEnum6 = <any> 'MY.atlasCodeEnum6',
        AtlasCodeEnum7 = <any> 'MY.atlasCodeEnum7',
        AtlasCodeEnum8 = <any> 'MY.atlasCodeEnum8',
        AtlasCodeEnum61 = <any> 'MY.atlasCodeEnum61',
        AtlasCodeEnum62 = <any> 'MY.atlasCodeEnum62',
        AtlasCodeEnum63 = <any> 'MY.atlasCodeEnum63',
        AtlasCodeEnum64 = <any> 'MY.atlasCodeEnum64',
        AtlasCodeEnum65 = <any> 'MY.atlasCodeEnum65',
        AtlasCodeEnum66 = <any> 'MY.atlasCodeEnum66',
        AtlasCodeEnum71 = <any> 'MY.atlasCodeEnum71',
        AtlasCodeEnum72 = <any> 'MY.atlasCodeEnum72',
        AtlasCodeEnum73 = <any> 'MY.atlasCodeEnum73',
        AtlasCodeEnum74 = <any> 'MY.atlasCodeEnum74',
        AtlasCodeEnum75 = <any> 'MY.atlasCodeEnum75',
        AtlasCodeEnum81 = <any> 'MY.atlasCodeEnum81',
        AtlasCodeEnum82 = <any> 'MY.atlasCodeEnum82'
    }
    export enum NativeStatusEnum {
        Native = <any> 'MY.native',
        NonNative = <any> 'MY.nonNative'
    }
    export enum PlantLifeStageEnum {
        PlantLifeStageSterile = <any> 'MY.plantLifeStageSterile',
        PlantLifeStageFertile = <any> 'MY.plantLifeStageFertile',
        PlantLifeStageSeed = <any> 'MY.plantLifeStageSeed',
        PlantLifeStageSprout = <any> 'MY.plantLifeStageSprout',
        PlantLifeStageBud = <any> 'MY.plantLifeStageBud',
        PlantLifeStageFlower = <any> 'MY.plantLifeStageFlower',
        PlantLifeStageWitheredFlower = <any> 'MY.plantLifeStageWitheredFlower',
        PlantLifeStageRipeningFruit = <any> 'MY.plantLifeStageRipeningFruit',
        PlantLifeStageRipeFruit = <any> 'MY.plantLifeStageRipeFruit',
        PlantLifeStageDeadSprout = <any> 'MY.plantLifeStageDeadSprout',
        PlantLifeStageSubterranean = <any> 'MY.plantLifeStageSubterranean',
        PlantLifeStageLivingPlant = <any> 'MY.plantLifeStageLivingPlant',
        PlantLifeStageDeadPlant = <any> 'MY.plantLifeStageDeadPlant'
    }
    export enum PlantStatusCodeEnum {
        MYPlantStatusCodeL = <any> 'MY.MY.plantStatusCodeL',
        PlantStatusCodeA = <any> 'MY.plantStatusCodeA',
        PlantStatusCodeAV = <any> 'MY.plantStatusCodeAV',
        PlantStatusCodeAOV = <any> 'MY.plantStatusCodeAOV',
        PlantStatusCodeAN = <any> 'MY.plantStatusCodeAN',
        PlantStatusCodeANV = <any> 'MY.plantStatusCodeANV',
        PlantStatusCodeANS = <any> 'MY.plantStatusCodeANS',
        PlantStatusCodeT = <any> 'MY.plantStatusCodeT',
        PlantStatusCodeTV = <any> 'MY.plantStatusCodeTV',
        PlantStatusCodeTOV = <any> 'MY.plantStatusCodeTOV',
        PlantStatusCodeTNV = <any> 'MY.plantStatusCodeTNV',
        PlantStatusCodeTNS = <any> 'MY.plantStatusCodeTNS',
        PlantStatusCodeV = <any> 'MY.plantStatusCodeV',
        PlantStatusCodeOV = <any> 'MY.plantStatusCodeOV',
        PlantStatusCodeN = <any> 'MY.plantStatusCodeN',
        PlantStatusCodeNV = <any> 'MY.plantStatusCodeNV',
        PlantStatusCodeNS = <any> 'MY.plantStatusCodeNS',
        PlantStatusCodeE = <any> 'MY.plantStatusCodeE',
        PlantStatusCodeTE = <any> 'MY.plantStatusCodeTE',
        PlantStatusCodeTVE = <any> 'MY.plantStatusCodeTVE',
        PlantStatusCodeTOVE = <any> 'MY.plantStatusCodeTOVE',
        PlantStatusCodeTNVE = <any> 'MY.plantStatusCodeTNVE',
        PlantStatusCodeTNSE = <any> 'MY.plantStatusCodeTNSE',
        PlantStatusCodeTN = <any> 'MY.plantStatusCodeTN',
        PlantStatusCodeTNE = <any> 'MY.plantStatusCodeTNE',
        PlantStatusCodeR = <any> 'MY.plantStatusCodeR',
        PlantStatusCodeC = <any> 'MY.plantStatusCodeC',
        PlantStatusCodeH = <any> 'MY.plantStatusCodeH',
        PlantStatusCodeG = <any> 'MY.plantStatusCodeG',
        PlantStatusCodeF = <any> 'MY.plantStatusCodeF'
    }
    export enum PreservationEnum {
        PreservationPinned = <any> 'MY.preservationPinned',
        PreservationGlued = <any> 'MY.preservationGlued',
        PreservationEthanol = <any> 'MY.preservationEthanol',
        PreservationEthanolPure = <any> 'MY.preservationEthanolPure',
        PreservationEthanol96 = <any> 'MY.preservationEthanol96',
        PreservationEthanol80 = <any> 'MY.preservationEthanol80',
        PreservationEthanol80Pure = <any> 'MY.preservationEthanol80Pure',
        PreservationEthanol70 = <any> 'MY.preservationEthanol70',
        PreservationEthanolDenatured = <any> 'MY.preservationEthanolDenatured',
        PreservationFormalin = <any> 'MY.preservationFormalin',
        PreservationEthanolFormalin = <any> 'MY.preservationEthanolFormalin',
        PreservationGlycerol = <any> 'MY.preservationGlycerol',
        PreservationLiquid = <any> 'MY.preservationLiquid',
        PreservationEulan = <any> 'MY.preservationEulan',
        PreservationSlide = <any> 'MY.preservationSlide',
        PreservationSlideEuparal = <any> 'MY.preservationSlideEuparal',
        PreservationSlidePolyviol = <any> 'MY.preservationSlidePolyviol',
        PreservationSlideCanadaBalsam = <any> 'MY.preservationSlideCanadaBalsam',
        PreservationCriticalPointDrying = <any> 'MY.preservationCriticalPointDrying',
        PreservationGoldPlated = <any> 'MY.preservationGoldPlated',
        PreservationFreezeDried = <any> 'MY.preservationFreezeDried',
        PreservationFrozen = <any> 'MY.preservationFrozen',
        PreservationDry = <any> 'MY.preservationDry',
        PreservationStuffed = <any> 'MY.preservationStuffed',
        PreservationParaffin = <any> 'MY.preservationParaffin',
        PreservationPressed = <any> 'MY.preservationPressed',
        PreservationLiving = <any> 'MY.preservationLiving',
        PreservationCast = <any> 'MY.preservationCast',
        PreservationEthanolExFormalin = <any> 'MY.preservationEthanolExFormalin'
    }
    export enum SmellEnum {
        SmellNotSmelled = <any> 'MY.smellNotSmelled',
        SmellNoSmelled = <any> 'MY.smellNoSmelled',
        SmellWeak = <any> 'MY.smellWeak',
        SmellModerate = <any> 'MY.smellModerate',
        SmellStrong = <any> 'MY.smellStrong'
    }
    export enum SubstrateClassificationEnum {
        SubstrateOrganicLiving = <any> 'MY.substrateOrganicLiving',
        SubstrateOrganicDeceased = <any> 'MY.substrateOrganicDeceased',
        SubstrateInorganic = <any> 'MY.substrateInorganic'
    }
    export enum TasteEnum {
        TasteNotTasted = <any> 'MY.tasteNotTasted',
        TasteNoTaste = <any> 'MY.tasteNoTaste',
        TasteWeak = <any> 'MY.tasteWeak',
        TasteModerate = <any> 'MY.tasteModerate',
        TasteStrong = <any> 'MY.tasteStrong'
    }
    export enum TaxonConfidenceEnum {
        TaxonConfidenceSure = <any> 'MY.taxonConfidenceSure',
        TaxonConfidenceUnsure = <any> 'MY.taxonConfidenceUnsure',
        TaxonConfidenceSubspeciesUnsure = <any> 'MY.taxonConfidenceSubspeciesUnsure'
    }
}
